### ISSUE TITLE
Not able to open an instance of google chrome with DevTools

### ISSUE THREAD

**Issue by Forest-Dewberry** [marty90/PyChromeDevTools#12]
I am working on a macbook pro Retina, 13-inch, Late 2012. High Sierra OS verision 10.13.15 (17F77)

My problem is that I am attempting to open Chrome with the remote debugging port option and the program stalls in terminal. I have to press ^C, killing the process, because otherwise it just sits there. Here is what I see in my terminal:

```
(3rdPartyInstagramApp) iphone:debugger-protocol-viewer forestdewberry$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --user-data-dir=remote-profile

DevTools listening on ws://127.0.0.1:9222/devtools/browser/25b29bd9-3b71-4f5a-b2f8-bc97d0ba2ed5
2018-07-15 16:26:42.302 Google Chrome[48614:4393942] *** Owner supplied to -[NSTrackingArea initWithRect:options:owner:userInfo:] referenced a deallocating object. Tracking area behavior is undefined. Break on NSTrackingAreaDeallocatingOwnerError to debug.
2018-07-15 16:26:56.076 Google Chrome[48614:4393942] *** Owner supplied to -[NSTrackingArea initWithRect:options:owner:userInfo:] referenced a deallocating object. Tracking area behavior is undefined. Break on NSTrackingAreaDeallocatingOwnerError to debug.
^C(3rdPartyInstagramApp) iphone:debugger-protocol-viewer forestdewberry
```

What is causing this error and how do I fix it?

**Comment by Forest-Dewberry** [comment]
I found the solution. First of all, the fact that my program "stalled" in my terminal is not a problem - it simply means that the chrome process is ongoing. in order to resolve this apparent issue, which is more like a preference, I elected to open a different terminal, but I could have used:
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --user-data-dir=remote-profile&
```
The ampersand causes the program to run in the background.

Secondly, I had a problem executing:
```
>>> import PyChromeDevTools
>>> chrome =  PyChromeDevTools.ChromeInterface()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyChromeDevTools-0.1-py3.6.egg/PyChromeDevTools/__init__.py", line 43, in __init__
  File "/usr/local/lib/python3.6/site-packages/PyChromeDevTools-0.1-py3.6.egg/PyChromeDevTools/__init__.py", line 54, in connect
AttributeError: module 'websocket' has no attribute 'create_connection'
```
The cause of this error is that I had installed the wrong dependency with pip. Running "pip3 list" (I have two separate pip installations, one for python2.7 and one for python3, with symlinks pip and pip3 accordingly; if you only have python3 and use only one installation of pip, you're fine, don't worry about this) I got:
```
Package          Version  
---------------- ---------
certifi          2018.4.16
chardet          3.0.4    
cycler           0.10.0   
gevent           1.3.4    
greenlet         0.4.13   
idna             2.7      
kiwisolver       1.0.1    
numpy            1.14.1   
pip              10.0.1   
PyChromeDevTools 0.1      
pyparsing        2.2.0    
python-dateutil  2.7.0    
requests         2.19.1   
setuptools       38.5.2   
six              1.11.0   
urllib3          1.23     
**websocket        0.2.1    
websocket-client 0.48.0**   
wheel            0.30.0  
```

I uninstalled `websocket` then installed `websocket-client`, with this result:
```
(3rdPartyInstagramApp) MacBook-Pro:~ forestdewberry$ sudo -H pip3 uninstall websocket
Uninstalling websocket-0.2.1:
  Would remove:
    /usr/local/lib/python3.6/site-packages/websocket-0.2.1.dist-info/*
    /usr/local/lib/python3.6/site-packages/websocket/*
Proceed (y/n)? y
  Successfully uninstalled websocket-0.2.1
(3rdPartyInstagramApp) MacBook-Pro:~ forestdewberry$ sudo -H pip3 install websocket-client
Requirement already satisfied: websocket-client in /usr/local/lib/python3.6/site-packages/websocket_client-0.48.0-py3.6.egg (0.48.0)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from websocket-client) (1.11.0)
(3rdPartyInstagramApp) MacBook-Pro:~ forestdewberry$ sudo -H pip3 uninstall websocket-client
Uninstalling websocket-client-0.48.0:
  Would remove:
    /usr/local/lib/python3.6/site-packages/websocket_client-0.48.0-py3.6.egg
Proceed (y/n)? y
  Successfully uninstalled websocket-client-0.48.0
(3rdPartyInstagramApp) MacBook-Pro:~ forestdewberry$ sudo -H pip3 install websocket-client
Collecting websocket-client
  Downloading https://files.pythonhosted.org/packages/8a/a1/72ef9aa26cfe1a75cee09fc1957e4723add9de098c15719416a1ee89386b/websocket_client-0.48.0-py2.py3-none-any.whl (198kB)
    100% |████████████████████████████████| 204kB 1.4MB/s 
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from websocket-client) (1.11.0)
Installing collected packages: websocket-client
Successfully installed websocket-client-0.48.0
(3rdPartyInstagramApp) MacBook-Pro:~ forestdewberry$ python3
Python 3.6.4 (default, Mar  9 2018, 23:15:08) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyChromeDevTools
>>> chrome =  PyChromeDevTools.ChromeInterface()
>>> 
```
### It works!

**Comment by marty90** [comment]
Perfect;)
