### ISSUE TITLE
Error Connection refused

### ISSUE THREAD

**Issue by aldo-o** [marty90/PyChromeDevTools#2]
```
Traceback (most recent call last):
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10b4652b0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=1234): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b4652b0>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aldoec/PycharmProjects/untitled/index.py", line 3, in <module>
    chrome = PyChromeDevTools.ChromeInterface(host="127.0.0.1", port=1234)
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/PyChromeDevTools-0.1-py3.6.egg/PyChromeDevTools/__init__.py", line 43, in __init__
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/PyChromeDevTools-0.1-py3.6.egg/PyChromeDevTools/__init__.py", line 51, in connect
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/PyChromeDevTools-0.1-py3.6.egg/PyChromeDevTools/__init__.py", line 46, in get_tabs
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/aldoec/.virtualenvs/DjangoTest/lib/python3.6/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=1234): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b4652b0>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by marty90** [comment]
Did you start chrome before executing your script ?

**Comment by muslu** [comment]
Hello;

Same error. Chrome is open with remote debug.

`google-chrome --remote-debugging-port=9222`

and giving this error.

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9222): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7770ef8c50>: Failed to establish a new connection: [Errno 111] Connection refused',))`


end python file:
```
import PyChromeDevTools
import time

chrome = PyChromeDevTools.ChromeInterface()
chrome.Network.enable()
chrome.Page.enable()

start_time = time.time()
chrome.Page.navigate(url="http://www.muslu.com/")
chrome.wait_event("Page.loadEventFired", timeout=60)
end_time = time.time()

print ("Page Loading Time:", end_time - start_time)

```

**Comment by marty90** [comment]
This might be a problem on the Chrome side. Try the bash command
`curl http://localhost:9222/json/list`
and see if it fails or not.
