### ISSUE TITLE
Websocket times out in wait_event

### ISSUE THREAD

**Issue by akiarie** [marty90/PyChromeDevTools#5]
This happens before the timeout, and leads to the except/break.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "project.py", line 200, in some_method
    loadEvent, _ = self._chrome.wait_event('Page.loadEventFired', timeout=60)
  File "/path/to/project/PyChromeDevTools/__init__.py", line 84, in wait_event
    message = self.ws.recv()
  File "/path/to/project/PyChromeDevTools/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/path/to/project/PyChromeDevTools/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/path/to/project/PyChromeDevTools/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/path/to/project/PyChromeDevTools/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/path/to/project/PyChromeDevTools/websocket/_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "/path/to/project/PyChromeDevTools/websocket/_abnf.py", line 288, in recv_header
    header = self.recv_strict(2)
  File "/path/to/project/PyChromeDevTools/websocket/_abnf.py", line 375, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/path/to/project/PyChromeDevTools/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/path/to/project/PyChromeDevTools/websocket/_socket.py", line 83, in recv
    raise WebSocketTimeoutException(message)
PyChromeDevTools.websocket._exceptions.WebSocketTimeoutException: timed out
```

**Comment by marty90** [comment]
Did you start a chrome instance before executing the script ?

**Comment by akiarie** [comment]
I did, yes.
